server:
  servlet:
    context-path: /webapp
mspring:
  web:
    freemarker:
      template-path: /WEB-INF/classes/templates
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
